### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by bweston92** [steverhoades/expressive-async#2]
I currently have a few micro-services in Zend Expressive currently all of them are on PHP FPM, how-ever they require software like nginx/apache to handle the HTTP request which makes using Docker a whole lot harder.

Is this package classes as production ready, I see it is able to serve HTTP requests but have you had any issues with race conditions as this is obviously a for-ever running php script?

**Comment by steverhoades** [comment]
I would not consider this library production ready at this point.
